specials = [
    "Làm thế nào để đăng ký học phần?",
    "Hạn chót đăng ký học phần là khi nào?",
    "Quy trình rút học phần như thế nào?",
    "Học phí kỳ này là bao nhiêu?",
    "Có thể đóng học phí bằng hình thức nào?",
    "Hạn chót đóng học phí là khi nào?",
    "Có chính sách miễn giảm học phí không?",
    "Điều kiện để nhận học bổng là gì?",
    "Làm thế nào để xin gia hạn học phí?",
    "Làm thế nào để xác nhận tình trạng sinh viên?",
    "Làm thế nào để xin giấy xác nhận sinh viên?",
    "Tôi có thể xem lịch học ở đâu?",
    "Khi nào có lịch thi học kỳ?",
    "Tôi có thể đổi lớp học phần được không?",
    "Điều kiện để tốt nghiệp là gì?",
    "Tôi cần bao nhiêu tín chỉ để tốt nghiệp?",
    "Làm thế nào để chuyển ngành học?",
    "Quy trình xin bảo lưu kết quả học tập như thế nào?",
    "Làm thế nào để xin tạm ngừng học?",
    "Tôi cần làm gì để tiếp tục học sau khi bảo lưu?",
    "Thời gian tối đa để hoàn thành chương trình học là bao lâu?",
    "Điểm tối thiểu để qua môn là bao nhiêu?",
    "Tôi có thể phúc khảo điểm thi không? Quy trình thế nào?",
    "Có thể học lại một môn đã qua không?",
    "Làm thế nào để đăng ký học cải thiện điểm?",
    "Tôi có thể học song ngành không?",
    "Điều kiện để học song ngành là gì?",
    "Làm thế nào để đổi giảng viên?",
    "Nếu lịch học bị trùng, tôi nên làm gì?",
    "Tôi có thể học vượt không? Điều kiện là gì?",
    "Học kỳ hè được tổ chức như thế nào?",
    "Tôi cần liên hệ với ai để giải quyết vấn đề học vụ?",
    "Có khóa học trực tuyến không?",
    "Tôi có thể học các môn ngoài trường không?",
    "Làm thế nào để chuyển điểm từ trường khác?",
    "Chính sách học bổng của trường là gì?",
    "Học phí có tăng qua từng năm không?",
    "Làm thế nào để xin hỗ trợ tài chính?",
    "Tôi cần bao nhiêu tín chỉ trong một kỳ học?",
    "Học lực trung bình có ảnh hưởng đến việc tốt nghiệp không?",
    "Tôi cần làm gì nếu không đạt số tín chỉ tối thiểu trong kỳ?",
    "Có thể đăng ký thêm tín chỉ ngoài số tín chỉ tối đa không?",
    "Trường có yêu cầu thực tập không? Điều kiện là gì?",
    "Tôi có thể xin hoãn thực tập không?",
    "Tôi cần nộp báo cáo thực tập vào lúc nào?",
    "Có khóa học bổ trợ nào cho sinh viên không?",
    "Trường có hỗ trợ sinh viên quốc tế không?",
    "Tôi cần làm gì nếu muốn học ở nước ngoài qua chương trình trao đổi?",
    "Trường có chương trình học bổng cho sinh viên quốc tế không?",
    "Có các câu lạc bộ học thuật nào trong trường không?",
    # "Điểm trung bình tích lũy (GPA) được tính như thế nào?",
    # "Làm thế nào để kiểm tra điểm của mình?",
    # "Điểm F có ảnh hưởng đến GPA không?",
    # "Nếu bị đình chỉ học, tôi cần làm gì?",
    # "Tôi có thể xin học lại sau khi bị đình chỉ không?",
    # "Quy trình xét tốt nghiệp diễn ra khi nào?",
    # "Nếu không đủ tín chỉ tốt nghiệp, tôi nên làm gì?",
    # "Chương trình học của tôi có thay đổi không?",
    # "Nếu chương trình học thay đổi, tôi có bị ảnh hưởng không?",
    # "Làm thế nào để nhận bảng điểm chính thức?",
    # "Có thể nhận bằng tốt nghiệp trước ngày phát bằng chính thức không?",
    # "Làm thế nào để đổi ngành học khi đang học dở?",
    # "Tôi cần làm gì để học chương trình liên kết quốc tế?",
    # "Trường có chương trình đào tạo ngắn hạn không?",
    # "Tôi cần liên hệ ai để biết thêm thông tin về ngành học của mình?",
    # "Làm thế nào để gia hạn thời gian nộp luận văn?",
    # "Tôi cần đăng ký ở đâu để bảo vệ luận văn?",
    # "Tôi có thể sử dụng tài nguyên thư viện online không?",
    # "Có các workshop kỹ năng mềm nào dành cho sinh viên không?",
    # "Trường có hỗ trợ việc làm sau tốt nghiệp không?",
    # "Có chương trình thực tập nào do trường giới thiệu không?",
    # "Làm thế nào để tham gia chương trình liên kết đào tạo quốc tế?",
    # "Tôi có thể chuyển tiếp lên chương trình thạc sĩ ngay sau khi tốt nghiệp không?",
    # "Trường có yêu cầu ngoại ngữ đầu ra không?",
    # "Tôi cần trình độ ngoại ngữ nào để tốt nghiệp?",
    # "Làm thế nào để đăng ký thi chứng chỉ ngoại ngữ tại trường?",
    # "Tôi cần liên hệ ai để giải quyết vấn đề thời khóa biểu?",
    # "Tôi cần làm gì nếu bị gián đoạn trong chương trình học?",
    # "Quy định về việc học bù là gì?",
    # "Trường có hỗ trợ sinh viên khuyết tật không?",
    # "Có các dịch vụ tư vấn học tập không?",
    # "Tôi có thể thay đổi khóa luận tốt nghiệp bằng thực tập không?",
    # "Làm thế nào để nhận giấy mời nhập học?",
    # "Có chương trình liên thông từ cao đẳng lên đại học không?",
    # "Học phí có bao gồm tài liệu học tập không?",
    # "Nếu mất thẻ sinh viên, tôi cần làm gì?",
    # "Có thể học lại môn đã được miễn tín chỉ không?",
    # "Tôi cần chuẩn bị gì khi làm thủ tục nhập học?",
    # "Có chương trình học trực tuyến kết hợp không?",
    # "Tôi cần làm gì để xác nhận các giấy tờ cho công việc?",
    # "Hệ thống quản lý học tập online của trường là gì?",
    # "Tôi cần liên hệ phòng nào để biết về nội dung chương trình học?"
]

chitchats = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Chào bạn, tên bạn là gì?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?",
    "Bạn có khỏe không?",
    "Bạn đang làm gì vậy?",
    "Bạn thích mùa nào nhất?",
    "Hôm nay bạn có bận không?",
    "Có kế hoạch gì cho cuối tuần không?",
    "Bạn thích món ăn nào nhất?",
    "Bạn đã từng đi du lịch chưa?",
    "Thành phố yêu thích của bạn là gì?",
    "Bạn có thích đọc sách không?",
    "Bạn có thích nghe nhạc không?",
    "Bài hát yêu thích của bạn là gì?",
    "Bạn thích ban nhạc nào nhất?",
    "Bạn có biết chơi nhạc cụ nào không?",
    "Bạn có thích thể thao không?",
    "Môn thể thao yêu thích của bạn là gì?",
    "Bạn nghĩ đội bóng nào sẽ vô địch mùa này?",
    "Bạn có chơi game không?",
    "Game yêu thích của bạn là gì?",
    "Bạn có thích động vật không?",
    "Con vật yêu thích của bạn là gì?",
    # "Bạn thích mèo hay chó hơn?",
    # "Bạn có nuôi thú cưng không?",
    # "Màu sắc yêu thích của bạn là gì?",
    # "Bạn thích loại thời tiết nào?",
    # "Bạn có sợ bóng tối không?",
    # "Bạn có thích đi xem phim không?",
    # "Bộ phim gần đây nhất bạn xem là gì?",
    # "Bạn có thích phim kinh dị không?",
    # "Bạn có hay uống cà phê không?",
    # "Bạn thích trà hay cà phê hơn?",
    # "Bạn có thích nấu ăn không?",
    # "Món ăn bạn nấu ngon nhất là gì?",
    # "Bạn có thích đi mua sắm không?",
    # "Bạn thường mua sắm ở đâu?",
    # "Bạn có thích mùa hè không?",
    # "Bạn thích làm gì vào mùa đông?",
    # "Bạn đã bao giờ nhìn thấy tuyết chưa?",
    # "Bạn có thích leo núi không?",
    # "Bạn có thích biển không?",
    # "Kỳ nghỉ mơ ước của bạn là gì?",
    # "Bạn có biết bơi không?",
    # "Bạn có thích chạy bộ không?",
    # "Bạn có thích yoga không?",
    # "Bạn có thích làm vườn không?",
    # "Bạn đã từng trồng cây chưa?",
    # "Bạn có thích làm bánh không?",
    # "Bạn có thích nghe podcast không?",
    # "Chủ đề podcast yêu thích của bạn là gì?",
    # "Bạn có thích hài kịch không?",
    # "Bạn có sợ độ cao không?",
    # "Bạn thích đi bộ đường dài không?",
    # "Bạn có thích đọc truyện tranh không?",
    # "Bạn có thích học ngôn ngữ mới không?",
    # "Bạn nói được bao nhiêu ngôn ngữ?",
    # "Ngôn ngữ bạn muốn học là gì?",
    # "Bạn có thích vẽ không?",
    # "Bạn đã từng tham gia một lớp học nghệ thuật chưa?",
    # "Bạn thích kiểu hội họa nào nhất?",
    # "Bạn có thích viết không?",
    # "Chủ đề yêu thích của bạn khi viết là gì?",
    # "Bạn có sợ côn trùng không?",
    # "Bạn có thích ngắm sao không?",
    # "Bạn có thích đi dạo vào ban đêm không?",
    # "Bạn đã từng thấy cầu vồng chưa?",
    # "Bạn có thích máy bay không?",
    # "Bạn đã từng đi du lịch bằng tàu hỏa chưa?",
    # "Bạn có thích đọc tin tức không?",
    # "Bạn thích loại báo nào?",
    # "Bạn có sợ ma không?",
    # "Bạn có tin vào UFO không?",
    # "Bạn có tin vào số mệnh không?",
    # "Bạn có tin vào duyên số không?",
    # "Bạn có thích những câu chuyện huyền bí không?",
    # "Bạn có thích sưu tầm đồ không?",
    # "Bạn đã từng tham gia một cuộc thi chưa?",
    # "Bạn có thích chơi cờ không?",
    # "Bạn đã từng đi xem hòa nhạc chưa?",
    # "Bạn có thích làm việc nhóm không?",
    # "Bạn có thích làm việc một mình không?",
    # "Bạn đã từng tham gia tình nguyện chưa?",
    # "Bạn có thích trẻ con không?",
    # "Bạn có sợ nói trước đám đông không?",
    # "Bạn có thích kể chuyện không?",
    # "Bạn có thường mơ không?",
    # "Bạn nhớ giấc mơ gần đây nhất không?",
    # "Bạn đã từng thử nhịn ăn chưa?",
    # "Bạn có thích ăn chay không?",
    # "Bạn có thích khám phá các nền văn hóa không?",
    # "Bạn có thích lịch sử không?",
    # "Bạn nghĩ tương lai sẽ thế nào?",
    # "Bạn đã từng viết nhật ký chưa?",
    # "Bạn có thích tự làm đồ handmade không?",
    # "Bạn đã từng tham gia một hội thảo chưa?",
    # "Bạn có thích gặp gỡ người mới không?",
    # "Bạn có thích trò chuyện không?",
    # "Bạn có thích các trò chơi giải đố không?",
    # "Bạn thích loại đồ uống nào nhất?"
]

