specials = [
    "Làm thế nào để đăng nhập vào lớp học GDQP trên Microsoft Teams?",
    "Tài khoản đăng nhập vào Teams có giống với tài khoản trường Kiến trúc không?",
    "Có những cách nào để xác minh khi đăng nhập vào Teams?",
    "Nếu không thấy mục 'Tham gia nhóm bằng mã' trên Teams thì phải làm sao?",
    "Mã ghi danh vào lớp học GDQP được cung cấp ở đâu?",
    "Có thể tìm thấy lớp học GDQP bằng cách nhập mã ghi danh vào ô tìm kiếm trên Teams không?",
    "Làm thế nào để tham gia lớp học GDQP sau khi nhập mã ghi danh?",
    "Sinh viên có thể đổi mật khẩu tài khoản GDQP không?",
    "Sinh viên gặp lỗi khi đăng nhập vào Teams thì cần liên hệ ai?",
    "Nếu quên mật khẩu tài khoản GDQP, sinh viên cần làm gì?",
    "Sinh viên nhận tài khoản ED bằng cách nào?",
    "Tại sao cần đăng ký tài khoản ED ngay sau khi đăng ký tín chỉ?",
    "Tài khoản ED được bàn giao sau bao nhiêu ngày?",
    "Làm thế nào để thi TOEIC đầu vào tại trường?",
    "Sinh viên không thi TOEIC đầu vào sẽ học lộ trình tiếng Anh như thế nào?",
    "Những sinh viên nào được miễn học Tiếng Anh Tăng cường 1 (TATC1)?",
    "Chi phí đăng ký tài khoản ED cho từng học phần là bao nhiêu?",
    "Thời gian sử dụng tài khoản ED được tính từ thời điểm nào?",
    "Học phần Tiếng Anh chuyên ngành có cần tài khoản ED không?",
    "Sinh viên ngành Kiến trúc Tiên tiến có cần đăng ký tài khoản ED không?",
    "Cách thức thanh toán khi đăng ký tài khoản ED là gì?",
    "Sinh viên có thể chuyển khoản đăng ký tài khoản ED cho nhiều học phần không?",
    "Sinh viên có thể sử dụng tài khoản ED của kỳ trước cho kỳ sau không?",
    "Thời gian học trực tuyến môn GDQP diễn ra từ ngày nào đến ngày nào?",
    "Môn GDQP được học trên phần mềm nào?",
    "Sinh viên phải làm gì để điểm danh trong lớp học GDQP?",
    "Thi kết thúc học phần GDQP được tổ chức trên phần mềm nào?",
    "Thi học phần GDQP có bao nhiêu câu hỏi và kéo dài bao lâu?",
    "Những nội dung nào được thi trực tuyến?",
    "Học phần Quân sự chung sẽ được học và thi ở đâu?",
    "Sinh viên có thể thi lại nếu không đạt trong lần thi đầu tiên không?",
    "Nếu không thể vào học hoặc thi được thì sinh viên cần liên hệ ai?",
    "Có yêu cầu gì về trang phục khi học và thi trực tuyến không?",
    "Sinh viên có thể sử dụng tài liệu trong lúc thi không?",
    "Nếu mất kết nối mạng khi đang thi GDQP, sinh viên cần làm gì?",
    "Lịch học của Tuần sinh hoạt công dân được công bố ở đâu?",
    "Nội dung của Tuần sinh hoạt công dân bao gồm những gì?",
    "Hình thức tổ chức Tuần sinh hoạt công dân là trực tiếp hay trực tuyến?",
    "Sinh viên cần chuẩn bị gì khi tham gia Tuần sinh hoạt công dân?",
    "Quy định về điểm danh trong Tuần sinh hoạt công dân như thế nào?",
    "Nếu sinh viên vắng mặt trong Tuần sinh hoạt công dân thì có thể tham gia lại không?",
    "Sinh viên có thể xem lại nội dung Tuần sinh hoạt công dân sau khi kết thúc không?",
    "Có thể đăng ký bổ sung khối lượng học tập không?",
    "Thủ tục rút bớt học phần đã đăng ký như thế nào?",
    "Sinh viên có thể đăng ký học lại hoặc học cải thiện không?",
    "Quy trình mở lớp học phần được thực hiện như thế nào?",
    "Có thể chuyển đổi học phần tương đương không?",
    "Cách thức đăng ký học phần Tiếng Anh tại trường như thế nào?",
    "Điều kiện để học vượt là gì?",
    "Có thể rút học phần sau khi đã đóng học phí không?",
    "Sinh viên có thể học cùng lúc hai ngành không?",
    "Sinh viên có thể nộp học phí online bằng cách nào?",
    "Thời hạn nộp học phí là bao lâu?",
    "Nếu sinh viên chưa nộp học phí đúng hạn thì có thể xử lý như thế nào?",
    "Sinh viên có thể xin miễn giảm học phí không?",
    "Có chính sách hỗ trợ học phí cho sinh viên khó khăn không?",
    "Làm thế nào để xin cấp bảng điểm?",
    "Sinh viên có thể xin xác nhận hoàn thành chương trình GDQP ở đâu?",
    "Thủ tục xin cấp bản sao văn bằng, chứng chỉ như thế nào?",
    "Thời gian xử lý hồ sơ xin cấp bằng tốt nghiệp là bao lâu?",
    "Sinh viên có thể xin xác nhận hoàn thành chương trình đào tạo không?",
    "Làm thế nào để đăng ký nhận bằng tốt nghiệp?",
    "Sinh viên có thể ủy quyền nhận bằng tốt nghiệp không?",
    "Nếu mất bằng tốt nghiệp, sinh viên có thể xin cấp lại không?",
    "Quy chế đánh giá kết quả rèn luyện sinh viên như thế nào?",
    "Sinh viên có thể tham gia hoạt động ngoại khóa nào?",
    "Có những câu lạc bộ nào trong trường dành cho sinh viên?",
    "Điều kiện để nhận học bổng của trường là gì?",
    "Sinh viên có thể khiếu nại điểm số nếu cảm thấy không công bằng không?",
    "Quy trình khiếu nại kết quả học tập như thế nào?",
    "Sinh viên có thể đổi ngành học trong trường không?",
    "Trường có hỗ trợ sinh viên tìm việc làm sau khi tốt nghiệp không?",
    "Sinh viên có thể liên hệ ai để được hỗ trợ về học tập?",
    "Quy định về việc sử dụng tài khoản email sinh viên như thế nào?",
    "Nếu mất thẻ sinh viên, làm thế nào để xin cấp lại?",
    "Có dịch vụ tư vấn tâm lý cho sinh viên không?",
    "Làm thế nào để tra cứu thông tin cá nhân trên hệ thống quản lý sinh viên?",
    "Sinh viên có thể đăng ký ở ký túc xá như thế nào?",
    "Có chương trình trao đổi sinh viên với các trường khác không?",
    "Sinh viên có thể tham gia thực tập ở đâu trong quá trình học?",
    "Có những khóa đào tạo kỹ năng mềm nào dành cho sinh viên?",
    "Sinh viên có thể tham gia các cuộc thi học thuật nào trong trường?",
    "Có chính sách gì hỗ trợ sinh viên khuyết tật không?",
    "Sinh viên có thể xin giấy giới thiệu thực tập ở đâu?",
    "Những hành vi nào bị coi là vi phạm quy chế sinh viên?",
    "Hình thức xử lý đối với sinh viên vi phạm nội quy là gì?",
    "Sinh viên bị đình chỉ học tập có thể quay lại học không?",
    "Quy định về kỷ luật khi thi cử là gì?",
    "Hình thức xử lý khi sinh viên bị phát hiện gian lận trong thi cử?",
]

chitchats = [
    "Bạn có khỏe không?",
    "Bạn đang làm gì vậy?",
    "Hôm nay bạn có bận không?",
    "Bạn có thể trò chuyện với tôi không?",
    "Bạn có thể nói chuyện với tôi cả ngày không?",
    "Bạn có thể giúp tôi giết thời gian không?",
    "Chúng ta có thể nói chuyện về điều gì thú vị không?",
    "Bạn có thấy ngày hôm nay đẹp không?",
    "Bạn thích buổi sáng hay buổi tối hơn?",
    "Nếu tôi chào bạn bằng ngôn ngữ khác, bạn có hiểu không?",
    "Bạn thích thể loại âm nhạc nào?",
    "Bạn có thích xem phim không?",
    "Bạn có thể gợi ý một bộ phim hay không?",
    "Bạn có biết bài hát nào đang thịnh hành không?",
    "Bạn thích thể loại sách nào?",
    "Bạn có thích thể thao không?",
    "Bạn có nghĩ rằng chơi game là một sở thích tốt không?",
    "Bạn thích đi du lịch không?",
    "Nếu có thể đi bất cứ đâu trên thế giới, bạn sẽ chọn nơi nào?",
    "Bạn có thích ẩm thực không?",
    "Hạnh phúc là gì theo bạn?",
    "Làm thế nào để có một cuộc sống ý nghĩa?",
    "Bạn nghĩ gì về tình bạn?",
    "Bạn có tin vào số phận không?",
    "Làm thế nào để duy trì động lực?",
    "Bạn có lời khuyên nào về cách quản lý thời gian không?",
    "Thế nào là một ngày hoàn hảo?",
    "Bạn nghĩ điều gì là quan trọng nhất trong cuộc sống?",
    "Bạn có thể sống mà không có công nghệ không?",
    "Bạn có nghĩ rằng tiền có thể mua được hạnh phúc không?",
    "Bạn có cảm xúc không?",
    "Bạn có thể cười không?",
    "Bạn có thể buồn không?",
    "Bạn có thích con người không?",
    "Bạn có thể mơ không?",
    "Bạn có ngủ không?",
    "Bạn có thích nói chuyện không?",
    "Bạn có sợ hãi điều gì không?",
    "Bạn có thể yêu không?",
    "Bạn có thể viết thơ không?",
    "Bạn có thể kể một câu chuyện cười không?",
    "Bạn có biết trò đùa nào hay không?",
    "Bạn có thể đoán được tôi đang nghĩ gì không?",
    "Bạn có thích chơi đố vui không?",
    "Bạn có thể đưa ra một câu đố thú vị không?",
    "Bạn có thể nói một câu nói truyền cảm hứng không?",
    "Bạn có thể giả giọng một nhân vật nổi tiếng không?",
    "Bạn có thể tạo ra một câu chuyện ngẫu nhiên không?",
    "Bạn có biết meme nào đang thịnh hành không?",
    "Bạn có thể nghĩ ra một trò chơi đơn giản không?",
    "Bạn nghĩ công nghệ sẽ phát triển như thế nào trong 50 năm tới?",
    "Bạn có nghĩ rằng AI sẽ thay thế con người không?",
    "Bạn có nghĩ rằng chúng ta sẽ có xe bay trong tương lai không?",
    "Bạn có tin rằng du hành thời gian có thể xảy ra không?",
    "Bạn có thể tưởng tượng thế giới trong 100 năm nữa trông như thế nào không?",
    "Bạn có tin rằng con người sẽ sống trên sao Hỏa không?",
    "Bạn có nghĩ rằng AI có thể trở thành bạn thân của con người không?",
    "Bạn có thể giúp tôi lập kế hoạch cho tương lai không?",
    "Bạn có tin rằng người máy sẽ có ý thức không?",
    "Bạn có thể dự đoán xu hướng công nghệ tiếp theo không?",
    "Bạn có biết về văn hóa Việt Nam không?",
    "Bạn có thể kể một điều thú vị về Nhật Bản không?",
    "Bạn có thích ẩm thực Ý không?",
    "Bạn có thể kể một câu chuyện lịch sử thú vị không?",
    "Bạn có thể nói một câu bằng tiếng Pháp không?",
    "Bạn có biết về các lễ hội truyền thống trên thế giới không?",
    "Bạn có thể giúp tôi học một ngôn ngữ mới không?",
    "Bạn có thể kể một sự thật thú vị về một quốc gia không?",
    "Bạn có thể nói về một nhân vật lịch sử vĩ đại không?",
    "Bạn có thể kể một câu chuyện dân gian thú vị không?",
    "Nếu bạn là một loài động vật, bạn sẽ là loài nào?",
    "Bạn có thể biến thành người không?",
    "Nếu bạn có thể du hành thời gian, bạn sẽ đi đâu?",
    "Bạn có nghĩ rằng người ngoài hành tinh tồn tại không?",
    "Bạn có tin vào ma quỷ không?",
    "Nếu bạn có một siêu năng lực, bạn muốn có gì?",
    "Bạn có thể sống dưới nước không?",
    "Nếu bạn có thể tạo ra một thế giới mới, nó sẽ trông như thế nào?",
    "Bạn có thích kẹo hay bánh hơn?",
    "Nếu bạn có thể có một bữa tối với bất kỳ ai trên thế giới, bạn sẽ chọn ai?",
    "Làm thế nào để tìm thấy đam mê của mình?",
    "Bạn có thể đưa ra một số lời khuyên về làm việc hiệu quả không?",
    "Bạn có thể giúp tôi lập danh sách việc cần làm không?",
    "Làm thế nào để vượt qua sự trì hoãn?",
    "Bạn có thể gợi ý một số cách thư giãn không?",
    "Bạn có thể giúp tôi lên kế hoạch một chuyến du lịch không?",
    "Bạn có thể gợi ý một thói quen buổi sáng tốt không?",
    "Làm thế nào để duy trì sự cân bằng giữa công việc và cuộc sống?",
    "Bạn có thể chia sẻ một câu chuyện thành công không?",
    "Bạn có thể giúp tôi xây dựng một thói quen lành mạnh không?",
]